name: Deploy Lambda Container Image

on:
 workflow_dispatch

jobs:
 build and deploy:
  run-on: ubuntu-latest
  
 steps:
   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Configure AWS Credentials  
     uses: aws-actions/configure-aws-credentials@v5.0.0  
     with:  
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: us-east-1



   - name: Login to Amazon ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v2

   - name: Build Docker image
     run: |
          docker build -t hello-lambda .
          docker tag hello-lambda:latest ${{steps.login-ecr.outputs.registry}}/hello-lambda:latest


   - name: Push Docker image to ECR
     run: |
          docker push ${{steps.login-ecr.outputs.registry}}/hello-lambda:latest

   - name: Deploy Lambda Fucntion
     uses: aws-actions/aws-lambda-deplou@v1
     with:
       function-name: hello-lambda
       image-uri: ${{steps.login-ecr.outputs.registry}}/hello-lambda:latest